#include <stdlib.h>
#include <string.h>

#include <fcntl.h>
#include <fcntl.h>


#include "externfunc.h"


LanguageStruct Word[] = {
	{"MENU",},
	{"UNLOCK",},
	{"MONITOR",},
	{"CALLCENTER",},
	{"MESSAGE",},
	{"SAFE_SATUS",},
	{"WEEK1",},
	{"WEEK2",},
	{"WEEK3",},
	{"WEEK4",},
	{"WEEK5",},
	{"WEEK6",},
	{"WEEK7",},
	{"YEAR"},
	{"MONTH",},
	{"DATE",},
	{"UNLOCK_SUCCESS",},
	{"QUIET_MODE",},
	{"QUIET_MODE_SUCCESS",},
	{"QUIET_MODE_EXIT",},
	{"CALL",},
	{"CALLING",},
	{"CALLING_FAIL",},
	{"ANSWER",},
	{"HANG_UP",},
	{"VEDIO_FAIL",},
	{"TALKING",},
	{"WATING",},
	{"LEFT_TIME",},
	{"SECOND",},
	{"CALLING_BUZY",},
	{"BACK",},
	{"UP",},
	{"DOWN",},
	{"CONFIRM",},
	{"ALARMNG_AND_DIS",},
	{"SET_ROOM_NUM",},
	{"SYSINFO",},
	{"DISARMING_PASSWD",},
	{"HELP",},
	{"LANGUAGE",},
	{"CANCEL",},
	{"INSERT_ALARMING_PASSWD",},
	{"ZONE",},
	{"ZONE1",},
	{"ZONE2",},
	{"ZONE3",},
	{"ZONE4",},
	{"ZONE5",},
	{"ZONE6",},
	{"ZONE7",},
	{"ZONE8",},
	{"OUT_ARLARM",},
	{"IN_ARLARM",},
	{"ALARM_SUCCESS",},
	{"ALARM_SUCCESS_SEND_TO_CENTER",},
	{"FORCE_ALARM_SUCCESS",},
	{"FORCE_ALARM_SUCCESS_SEND_TO_CENTER",},
	{"ALARM_FAIL",},
	{"DISALARM_SUCCESS",},
	{"DISALARM_SUCCESS_SEND_TO_CENTER",},
	{"INSERT_NEW_ALARMING_PASSWD",},
	{"INSERT_NEW_ALARMING_PASSWD_AGAIN",},
	{"INCORRECT_PASSWD",},
	{"UNSAME_PASSWD",},
	{"CHANGE_SUCCESS"},
	{"DEVICE_ALARMING"},
	{"INSERT_SETTING_PASSWD"},
	{"DEVICE_INFO",},
	{"GET_DEVICE_ID",},
	{"DEVICE_NUM",},
	{"SYSTEM_VERSION",},
	{"SOFTWARE_VERSION",},
	{"RELEASE_DATE",},
	{"IP_ADD",},
	{"NET_MASK",},
	{"GATE_WAY",},
	{"BUILD",},
	{"FLOOR",},
	{"ROOM",},
	{"MAC_ADD",},
	{"CENTER_IP"},
	{"DMK_IP"},
	{"GET_DEVICE_ID_ING",},
	{"GET_DEVICE_ID_SUCCESS"},
	{"GET_DEVICE_ID_FAIL"},
	{"CHOICE_LANGUAGE"},
	{"COMFIRM_AND_REBOOT"},
	{"UPDATING"},
	{"REBOOT"},
	{"UPDATE_FAIL"},
	{"CHECK_MESSAGE"},
	{"CLEAR_MESSAGE"},
	{"CHECK_LEAVE_MESSAGE"},
	{"MESSAGE_TITLE"},
	{"MESSAGE_TIME"},
	{"MESSAGE_WORD"},
	{"MESSAGE_CLEAR"},
	{"MESSAGE_CLEAR_ALL"},
	{"UNBROKEN_ALARMING"},
	{"MACHINE_BROKEN"},
	{"VOLUME_SET"},
	{"VOLUME_SET_OK"},
	{"VOLUME_SET_FAILED"},
	{"VOLUME_SET_TEN"},
	{"VOLUME_SET_ONE"},
	{"VOLUME_SET_EXIT"},
	{"NEXT"},
	{"SEARCHING_CENTER"},
	{"GETTING_ROOM_NUM"},
	{"GETTING_ROOM_NUM_FAIL"},
	{"SETTING_TMP_IP"},
	{"SELECT_CENTER"},
	{"SELECT_QH"},
	{"SELECT_DH"},
	{"SELECT_DYH"},
	{"SELECT_CH"},
	{"SELECT_FH"},
	{"SELECT_FJH"},
	{"DMK_NAME"},
	{"SETTING_OK_AND_SAVE"},
	{"SEND_DATA_ERROR"},
	{"PROCESSING"},
	{"RECORD"},
	{"TALK_RECORD"},
	{"ALARM_RECORD"},
	{"CALL_IN"},
	{"CALL_OUT"},
	{"SWITCH"},
	{"ALARM_WORD"},
	{"ALARM_TIME"},
	{"SWITCH_CLEAR_ALL"},
	{"CAN_NOT_CLEAR_ALARM"},
	{"RECOVER"},
	{"ELEVATOR_ARRIVED"},
	{"CALLING_ELEVATOR"},
	{"NO_DMK"},
	{"DEVICE_BUTTON1"},
	{"DEVICE_SMOG1"},
	{"DEVICE_INFRARED1"},
	{"DEVICE_DOOR_CONTACT1"},
	{"DEVICE_INFRARED2"},
	{"DEVICE_DOOR_CONTACT2"},
	{"DEVICE_GENERAL1"},
	{"DEVICE_GENERAL2"},
	{"LEAVE_RECORD"},
	{"FILE_NAME"},
	{"RECORD_TIME"},
	{"MEMERY_NOT_ENOUGH"},
	{"ELEVATOR"},
	{"NO_VIDEO"},
	{"TIME_SET"},
	{"TIME_SET_TIME"},
	{"TIME_SET_DATE"},
	{"TIME_SET_SYNC"},
	{"TIME_SET_SUCCESS"},
	{"DEVICE_TYPE_WRONG"},
	{"DEVICE_TYPE_MASTER"},
	{"DEVICE_TYPE_SLAVE"},
	{"DEVICE_TYPE"},
	{"PROTOCOL"},
	{"TALK_WITH_OTHER"},
	{"EDIT"},
	{"CALL_ADDRESS"},
	{"ADD"},
	{"DELETE"},
	{"ADD_SUCSEES"},
	{"CAN_NOT_SET_MYSELF_IP"},
	{"ADDRESS_EXIST"},
	{"SET_HOUSE_SUCSEES"},
	{"HOUSE_CLEAR"},
	{"HOUSE_CLEAR_ALL"},
	{"LIGHT_SET"},
	{"LIGHT_SET_SUCCESS"},
	{"HELP_OP"},
	{"HELP_CALL"},
	{"HELP_CLEAR"},
	{"HELP_CENTER"},
	{"PLEASE_INSERT_PHONE_NUM"},
	{"MONITOR_LOCAL"},
	{"MONITOR_COMM_ERR"},
	{"CARD_SUCCESS"},
	{"CARD_USELESS"},
	{"CARD_LOSS"},
	{"CARD_OVERDUE"},
	{"CARD_UNREGIST"},
	{"PHONE_NUM_DOT_EXIST"},
	{"HELP_PASSWORD"},
	{"HELP_CALL_USER"},
	{"HELP_CALL_CENTER"},
	{"HELP_LEAVE_WORD"},
	{"HELP_HAND_UP"},
	{"INSERT_UNLOCK_PASSWD"},
	{"SETTING_PRESS_KEY"},
	{"SETTING_USER"},
	{"SETTING_LOCAL"},
	{"SETTING_SYSTEM"},
	{"SETTING_PASSWORD"},
	{"SETTING_ACCESS"},
	{"SETTING_ELEVATOR"},
	{"SETTING_REBOOT"},
	{"SETTING_DEVTYPE"},
	{"SETTING_RETURN"},
	{"CLEAR_ALL"},
	{"FIND"},
	{"RECORD_NUM"},
	{"ROOM_NUM"},
	{"IP"},
	{"HELP_EDIT_IP"},
	{"HELP_BUTTON"},
	{"ROOM_NUM_SORT"},
	{"EXSIT"},
	{"NOT_EXSIT"},
	{"PLEASE_INSERT_IP"},
	{"SUCCESS"},
	{"FAILED"},
	{"CAN_NOT_DELETE_CENTER"},
	{"NET_SETTING"},
	{"SAVE"},
	{"GET_ID"},
	{"WRONG_FORMATE"},
	{"FRAME_PERIOD"},
	{"ALRM_DOOR"},
	{"ENABLE_ALRM_DOOR"},
	{"ENABLE_PASSWORD"},
	{"HELP_EDIT"},
	{"HELP_MENU"},
	{"SETTING"},
	{"PLEASE_INSERT_SIX_PASSWORD"},
	{"NEW_SYSTEM_PASSWORD"},
	{"NEW_SYSTEM_PASSWORD_CONFIRM"},
	{"NEW_UNLOCK_PASSWORD"},
	{"NEW_UNLOCK_PASSWORD_CONFIRM"},
	{"SYSTEM_PASSWORD"},
	{"UNLOCK_PASSWORD"},
	{"CARD_NUM"},
	{"CARD_TYPE"},
	{"CARD_TYPE_OWNER"},
	{"CARD_TYPE_MANAGE"},
	{"CARD_TYPE_TEMP"},
	{"CARD_TYPE_INVALID"},
	{"PLEASE_INSERT_CARD_NUM"},
	{"HOUR"},
	{"MINUTE"},
	{"HELP_SYNC_TIME"},
	{"ELEVATOR_ADDRESS"},
	{"FLOOR_NUM"},
	{"ENABLE_ELEVATOR"},
	{"SINGLE_VERSION"},
	{"HELP_TOPMESSAGE"},
	{"CONFIRM_CLEAR_ALL_IP"},
	{"CONFIRM_CLEAR_ALL_CARD"},
	{"HELP_EDIT_ELEVATOR"},
	{"DOOR_OPEN"},
	{"DOOR_CLOSED"},
	{"DOOR_OPEN_TOO_LONG"},
	{"ENABLE_UNBROKEN"},
	{"LEAVE_MESSAGE_ING"},
	{"YEAR_ENC"},
	{"MONTH_ENC"},
	{"DATE_ENC"},
	{"ELEVATOR_LOBBY"},
	{"UPDATE_CARD"},
	{"UPDATE_CARD_SUCCESS"},
	{"UPDATE_CARD_FAIL"},
	{"UPDATE_USER"},
	{"UPDATE_USER_SUCCESS"},
	{"UPDATE_USER_FAIL"},
	{"WORD_CONTACT_LIST"},
	{"WORD_USERSEARCH_TITLE"},
	{"WORD_USERSEARCH_HELP"},
	{"WORD_UNIT"},
	{"WORD_NO_UNIT"},
};


int languageLoad(void)
{
	GHANDLE hFile;
	unsigned int i;
	if (Public.language == CHINEASE) {
		hFile = LoadEtcFile("Language_cn.ini");
		strncpy(font_type,"ttf",strlen("ttf"));
		strncpy(font_family,"song",strlen("song"));
		strncpy(font_charset,"GB2312",strlen("GB2312"));
	} else if (Public.language == TAIWAN) {
		hFile = LoadEtcFile("Language_cn.ini");
		strncpy(font_type,"ttf",strlen("ttf"));
		strncpy(font_family,"song",strlen("song"));
		strncpy(font_charset,"GB2312",strlen("GB2312"));
	}  else if (Public.language == ENGLISH) {
		hFile = LoadEtcFile("Language_en.ini");
		strncpy(font_type,"ttf",strlen("ttf"));
		strncpy(font_family,"arial",strlen("arial"));
		strncpy(font_charset,"ISO8859-1",strlen("ISO8859-1"));
	} else if (Public.language == TURKISH) {
		hFile = LoadEtcFile("Language_tu.ini");
		strncpy(font_type,"ttf",strlen("ttf"));
		strncpy(font_family,"arial",strlen("arial"));
		strncpy(font_charset,"ISO8859-9",strlen("ISO8859-9"));
	} else if (Public.language == RUSSIAN) {
		hFile = LoadEtcFile("Language_ru.ini");
		strncpy(font_type,"ttf",strlen("ttf"));
		strncpy(font_family,"arial",strlen("arial"));
		strncpy(font_charset,"ISO8859-5",strlen("ISO8859-5"));
	}else if (Public.language == UKRAINIAN) {
		hFile = LoadEtcFile("Language_uk.ini");
		strncpy(font_type,"ttf",strlen("ttf"));
		strncpy(font_family,"arial",strlen("arial"));
		strncpy(font_charset,"ISO8859-5",strlen("ISO8859-5"));
	}
	

	for (i=0; i<NELEMENTS(Word); i++) {
		if(GetValueFromEtc(hFile,"Language",Word[i].name,Word[i].string,sizeof(Word[i].string))!=ETC_OK) {
			printf("load string %s error\n",Word[i].name);
		}
	}
	UnloadEtcFile(hFile);
}


